<?php

return array(
    'shop_stock_plugin' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'enabled' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'img' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'description' => array('text', 'null' => 0),
        'homepage' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'datetime_begin' => array('datetime', 'null' => 0),
        'datetime_end' => array('datetime', 'null' => 0),
        'restart' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'begin_time' => array('time', 'null' => 0),
        'duration_time' => array('int', 11, 'null' => 0),
        'restart_period' => array('text', 'null' => 0),
        'period_begin' => array('datetime', 'null' => 1),
        'period_end' => array('datetime', 'null' => 1),
        'period_runing' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'type' => array('enum', "'discount','gift','bonus'", 'null' => 0, 'default' => 'discount'),
        'discount_type' => array('enum', "'percent','absolute','price'", 'null' => 0, 'default' => 'percent'),
        'discount_algorithm' => array('enum', "'replace','standart'", 'null' => 0, 'default' => 'replace'),
        'discount_value' => array('decimal', "15,4", 'null' => 0, 'default' => '0'),
        'gift_sku_id' => array('int', 11, 'null' => 0),
        'promocode_only' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'promocode' => array('varchar', 32, 'null' => 0, 'default' => ''),
        'absolute_bonus' => array('int', 11, 'null' => 0),
        'product_percent_bonus' => array('int', 11, 'null' => 0),
        'page_name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'page_url' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'page_title' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'meta_keywords' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'meta_description' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'page_content' => array('text', 'null' => 0),
        'params' => array('text', 'null' => 0),
        'badge' => array('varchar', 32, 'null' => 0, 'default' => ''),
        'badge_code' => array('text', 'null' => 0),
        'multiple_badges' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'rounding' => array('tinyint', 1, 'null' => 0, 'default' => '1'),
        ':keys' => array(
            'PRIMARY' => array('id'),
            'datetime_begin' => 'datetime_begin',
            'datetime_end' => 'datetime_end',
        ),
    ),
    'shop_stock_plugin_products' => array(
        'stock_id' => array('int', 11, 'null' => 0),
        'type' => array('enum', "'product','set','category','type','feature'", 'null' => 0, 'default' => 'product'),
        'value' => array('varchar', 64, 'null' => 0, 'default' => ''),
        'count' => array('int', 11, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'stock_id' => 'stock_id',
        ),
    ),
    'shop_stock_plugin_products_join' => array(
        'stock_id' => array('int', 11, 'null' => 0),
        'product_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'stock_id' => 'stock_id',
            'product_id' => 'product_id',
        ),
    ),
    'shop_stock_plugin_storefront' => array(
        'stock_id' => array('int', 11, 'null' => 0),
        'route_hash' => array('varchar', 32, 'null' => 0, 'default' => ''),
        ':keys' => array(
            'stock_id' => 'stock_id',
            'route_hash' => 'route_hash',
        ),
    ),
);
