<?php

$plugin_id = array('shop', 'stock');
$app_settings_model = new waAppSettingsModel();
$app_settings_model->set($plugin_id, 'status', '1');
$app_settings_model->set($plugin_id, 'stock_page', '1');
$app_settings_model->set($plugin_id, 'page_url', 'stock/');
$app_settings_model->set($plugin_id, 'page_name', 'Акции');
$app_settings_model->set($plugin_id, 'page_title', '');
$app_settings_model->set($plugin_id, 'meta_keywords', '');
$app_settings_model->set($plugin_id, 'meta_description', '');
$app_settings_model->set($plugin_id, 'page_template', 'page.html');
$app_settings_model->set($plugin_id, 'stock_page_template', 'search.html');
$app_settings_model->set($plugin_id, 'cart_products_template', 'list-thumbs.html');
$app_settings_model->set($plugin_id, 'frontend_product_output', 'block_aux');
$app_settings_model->set($plugin_id, 'frontend_category_output', '1');
$app_settings_model->set($plugin_id, 'countdown_range_hi', 'day');
$app_settings_model->set($plugin_id, 'countdown_width', '');
$app_settings_model->set($plugin_id, 'countdown_height', '');
$app_settings_model->set($plugin_id, 'countdown_style', 'boring');
$app_settings_model->set($plugin_id, 'countdown_hide_line', 'false');
$app_settings_model->set($plugin_id, 'countdown_hide_labels', 'false');
$app_settings_model->set($plugin_id, 'countdown_hide_labels', 'false');
$app_settings_model->set($plugin_id, 'countdown_second_text', 'Секунды');
$app_settings_model->set($plugin_id, 'countdown_minute_text', 'Минуты');
$app_settings_model->set($plugin_id, 'countdown_hour_text', 'Часы');
$app_settings_model->set($plugin_id, 'countdown_day_text', 'Дни');
$app_settings_model->set($plugin_id, 'countdown_month_text', 'Месяцы');
$app_settings_model->set($plugin_id, 'countdown_year_text', 'Годы');
$app_settings_model->set($plugin_id, 'countdown_numbers_color', '#FFFFFF');
$app_settings_model->set($plugin_id, 'countdown_numbers_bkgd', '#365D8B');
$app_settings_model->set($plugin_id, 'countdown_labels_color', '#000000');
$app_settings_model->set($plugin_id, 'countdown_labels_size', '0.7');
